# Generated by Django 3.2.13 on 2023-04-21 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_review_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ManyToManyField(related_name='movie', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
